import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import {
  StateSchema,
  MessagesValue,
  type GraphNode,
  StateGraph,
  START,
  END,
  ReducedValue,
} from "@langchain/langgraph";
import { createAgent, providerStrategy } from "langchain";
import { z } from "zod";
import {
  cohere_model,
  gemini_model,
  mistral_model,
} from "./models.services.js";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judege_response: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solutio_1_reasoning: z.string().default(""),
    solutio_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof State> = async (state: typeof State) => {
  const [mistral_response, cohere_response] = await Promise.all([
    mistral_model.invoke(state.problem),
    cohere_model.invoke(state.problem),
  ]);
  return {
    solution_1: mistral_response.content,
    solution_2: cohere_response.content,
  };
};

const judgeNode: GraphNode<typeof State> = async (state: typeof State) => {
  const judge = createAgent({
    model: gemini_model,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solutio_1_reasoning: z.string(),
        solutio_2_reasoning: z.string(),
      }),
    ),
    systemPrompt:
      "`You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores",
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`You are a judge tasked with evaluating the quality of two solution to a problem. The
                problem is: ${state.problem}. The first solution is: ${state.solution_1}. The second 
                solution is: ${state.solution_2}. Please provide a score between 0 and 10 for each solution, 
                where 0 means the solution is completely incorrect or irrelevant, and 10 means the solution is 
                perfect and fully addresses the problem`),
    ],
  });
  const result = judgeResponse.structuredResponse;

  return {
    judege_response: result,
  };
};

const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("judge", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge")
  .addEdge("judge", END)
  .compile();

export default async function (userMessage: string) {
  const result = await graph.invoke({
    problem: userMessage,
  });
  return result;
}
